# Generated by Django 4.1.7 on 2023-03-19 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('position', models.CharField(choices=[('ProjectManager', 'Project Manager'), (
                    'TeamLead', 'Team Lead'), ('Devoper', 'Devoper'), ('Tester', 'Tester')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=520)),
                ('completed', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assign', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams', to='mainApp.team')),
            ],
        ),
    ]
