# Generated by Django 4.1.7 on 2023-02-18 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('image', models.ImageField(upload_to='images/')),
                ('brand_name', models.TextField(max_length=20)),
                ('model', models.TextField(max_length=20)),
                ('sn_number', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('purchase_date', models.DateField()),
                ('expire_Date', models.DateField()),
                ('price', models.TextField(max_length=10)),
                ('invoice_img', models.ImageField(upload_to='invoices/')),
                ('status', models.TextField(max_length=10)),
                ('report', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AssetReportList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('issue', models.TextField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('status', models.TextField(max_length=10)),
                ('message', models.TextField(max_length=20)),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asset.asset')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetAssigningList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('expire_Date', models.DateField()),
                ('status', models.TextField(max_length=10)),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asset.asset')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
